name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        key: build-artifacts
        path: |
          ./build/* 
          ./ninja
    - name: install lua and gcc
      run: sudo apt install -y gcc lua5.4 python3
    - name: setup
      run: ./ci.sh setup
    - name: build
      run: ./ci.sh build
    - name: tests
      run: ./ci.sh test
