name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install lua and gcc
      run: sudo apt install -y gcc lua5.4
    - name: build
      run: ./ci.sh
